#!/bin/bash

# Hardcoded list of company names
companies=(
    "walmart"
    "target" 
    "dollar_general"
    "dollar_tree"
    "five_below"
    "costco"
    "bjs"
    "tj_maxx"
    "ross"
    "burlington"
    "macys"
    "nordstrom"
    "dillards"
    "kohls"
    "amazon"
    "wayfair"
    "chewy"
    "ulta_beauty"
    "bbb"
    "victorias_secret"
    "signet_jewelers"
    "tapestry"
    "capri_holdings"
    "lululemon"
    "boot_barn"
    "footlocker"
    "nike"
    "af"
    "american_eagle"
    "urban_outfitters"
    "gap"
    "levi"
    "dicks"
    "academy_sports"
    "best_buy"
    "yeti"
    "sherwin_williams"
    "rh"
    "william_sonoma"
    "home_depot"
    "lowes"
    "tractor_supply"
    "kroger"
    "albertsons"
    "walgreens"
    "cvs"
    "rite_aid"
)

# Process each company
for company in "${companies[@]}"; do
    period="2024:2024"
    echo "Executing: python process_filings.py $company $period"
    python process_filings.py "$company" "$period" 
done
